let data = ["Believe you can and you're halfway there.",
"Your time is limited, don't waste it living someone else's life.",
"The only way to do great work is to love what you do.",
"Dream big, work hard, stay focused.",
"Success is not final, failure is not fatal: It is the courage to continue that counts.",
"The only limit to our realization of tomorrow will be our doubts of today.",
"You are never too old to set another goal or to dream a new dream.",
"Don't watch the clock; do what it does. Keep going.",
"The future belongs to those who believe in the beauty of their dreams.",
"Strive not to be a success, but rather to be of value.",
"Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work.",
"The only person you are destined to become is the person you decide to be.",
"It always seems impossible until it's done.",
"The best way to predict the future is to create it.",
"Opportunities don't happen. You create them.",
"Success usually comes to those who are too busy to be looking for it.",
"Don't be afraid to give up the good to go for the great.",
"The only limit to our realization of tomorrow will be our doubts of today.",
"Success is stumbling from failure to failure with no loss of enthusiasm.",
"If you are not willing to risk the usual, you will have to settle for the ordinary.",
"Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.",
"I find that the harder I work, the more luck I seem to have.",
"It's not whether you get knocked down, it's whether you get up.",
"The only place where success comes before work is in the dictionary.",
"I didn’t fail the test. I just found 100 ways to do it wrong.",
"The road to success and the road to failure are almost exactly the same.",
"You don't have to be great to start, but you have to start to be great.",
"The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it.",
"The only way to achieve the impossible is to believe it is possible.",
"Don't wait. The time will never be just right.",
"Do not wait to strike till the iron is hot, but make it hot by striking.",
"The only place where success comes before work is in the dictionary.",
"Success is not in what you have, but who you are.",
"Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.",
"Success is not final, failure is not fatal: It is the courage to continue that counts.",
"Your time is limited, don't waste it living someone else's life.",
"Believe you can and you're halfway there.",
"The only limit to our realization of tomorrow will be our doubts of today.",
"The future belongs to those who believe in the beauty of their dreams.",
"Strive not to be a success, but rather to be of value.",
"The only person you are destined to become is the person you decide to be.",
"It always seems impossible until it's done.",
"The best way to predict the future is to create it.",
"Opportunities don't happen. You create them.",
"Success usually comes to those who are too busy to be looking for it.",
"Don't be afraid to give up the good to go for the great.",
"The only limit to our realization of tomorrow will be our doubts of today.",
"Success is stumbling from failure to failure with no loss of enthusiasm.",
"If you are not willing to risk the usual, you will have to settle for the ordinary.",
"Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.",
"I find that the harder I work, the more luck I seem to have.",
"It's not whether you get knocked down, it's whether you get up.",
"The only place where success comes before work is in the dictionary.",
"I didn’t fail the test. I just found 100 ways to do it wrong.",
"The road to success and the road to failure are almost exactly the same.",
"You don't have to be great to start, but you have to start to be great.",
"The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it.",
"The only way to achieve the impossible is to believe it is possible.",
"Don't wait. The time will never be just right.",
"Do not wait to strike till the iron is hot, but make it hot by striking.",
"The only place where success comes before work is in the dictionary.",
"Success is not in what you have, but who you are.",
"Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.",
"Success is not final, failure is not fatal: It is the courage to continue that counts.",
"Your time is limited, don't waste it living someone else's life.",
"Believe you can and you're halfway there.",
"The only limit to our realization of tomorrow will be our doubts of today.",
"The future belongs to those who believe in the beauty of their dreams.",
"Strive not to be a success, but rather to be of value.",
"The only person you are destined to become is the person you decide to be.",
"It always seems impossible until it's done.",
"The best way to predict the future is to create it.",
"Opportunities don't happen. You create them.",
"Success usually comes to those who are too busy to be looking for it.",
"Don't be afraid to give up the good to go for the great.",
"The only limit to our realization of tomorrow will be our doubts of today.",
"Success is stumbling from failure to failure with no loss of enthusiasm.",
"If you are not willing to risk the usual, you will have to settle for the ordinary.",
"Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.",
"I find that the harder I work, the more luck I seem to have.",
"It's not whether you get knocked down, it's whether you get up.",
"The only place where success comes before work is in the dictionary.",
"I didn’t fail the test. I just found 100 ways to do it wrong.",
"The road to success and the road to failure are almost exactly the same.",
"You don't have to be great to start, but you have to start to be great.",
"The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it.",
"The only way to achieve the impossible is to believe it is possible.",
"Don't wait. The time will never be just right.",
"Do not wait to strike till the iron is hot, but make it hot by striking.",
"The only place where success comes before work is in the dictionary.",
"Success is not in what you have, but who you are.",
"Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.",
"Success is not final, failure is not fatal: It is the courage to continue that counts.",
"Your time is limited, don't waste it living someone else's life.",
"Believe you can and you're halfway there.",
"The only limit to our realization of tomorrow will be our doubts of today.",
"The future belongs to those who believe in the beauty of their dreams.",
"Strive not to be a success, but rather to be of value.",
"The only person you are destined to become is the person you decide to be.",
"It always seems impossible until it's done."]

module.exports = {data};